# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b510acf759c55318b1ed9ffe174f329bd8d973a6be7984afa889b334ccc2c5cc0f164d99427adc52f711bcc24646637e9a4a4973ba7950aad13698c8889aa3f4

test:
  secret_key_base: 7b9b4f2222d27e933cd6528cd30ac0660517c0089da1c2d1e594f5472f739a954fdc83ced21cd4b3aa7ed2368db5d0241772146dd1e3b01720f3e9e20c0346fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
